### ISSUE TITLE
Title Being Ignored

### ISSUE THREAD

**Issue by DarkMask100** [DoctorD1501/JAVMovieScraper#109]
I've noticed that JAVMS seems to ignore the title I either select or input and automatically uses the 2nd title that's populated during the scrape. 

For example I search for a movie and in the title box there's 2 options.
TITLE A
TITLE B

It will always, no matter what I change in JAVMS or manually change use TITLE B. Any way to fix this?

**Comment by DoctorD1501** [comment]
Yeah, the drop down thing is currently messed up. It used to return the title it got from each site and let you choose one, but now with amalgamation thrown into the mix, it doesn't do that any more due to some bugs I was getting with that.

Right now I think it returns the name of the movie as title a and the ID of the movie as title b. Do you have the setting called "Use Filename as Title When Scraping" enabled? That might be messing things up for you. If not, what are all the settings do you have enabled, because for me when I try things, I can pick Title A or Title B, hit write to file and have the title I picked show up in the title.

**Comment by DoctorD1501** [comment]
I'm no longer using the combo box for the title as it was too messed up and was causing issues. As such, this issue is no longer relevant and I'm closing it.
