### ISSUE TITLE
Japanese version of 1pondo is no solution

### ISSUE THREAD

**Issue by ws01459293** [DoctorD1501/JAVMovieScraper#113]
Japanese version of 1pondo is no solution

**Comment by DoctorD1501** [comment]
There are multiple issues right now causing 1pondo not to work - especially the Japanese site. I managed to fix some of them, but I got stumped in the end because it seems the site requires javascript turned on to properly load the actual data content. This only happens on the japanese site, oddly enough.

My current library I use to parse the HTML doesn't actually run javascript, so I would need to use a new library that can do this.

I'm going to mark this as "bug" and "help wanted" in case anybody else wants to do this as it seems like a lot of work that isn't at the top of my bucket lists of things to do. People can just scrape 1pondo from javbus for the time being to get Japanese data for 1pondo, for the time being.

**Comment by DoctorD1501** [comment]
By the way, I've committed my changes I made to partially fix this, in case anybody else wants to take a crack at it.
