### ISSUE TITLE
missing actors

### ISSUE THREAD

**Issue by hentman** [DoctorD1501/JAVMovieScraper#126]
for some reason, when scraping Mum-165.mp4 only one actor is obtained "riona minami", there are 3 actors:
http://www.javlibrary.com/en/?v=javliiqhqi

**Comment by DoctorD1501** [comment]
This one is not something I can do anything about, at least cleanly. If you use "Scrape Adult Amalgamated JAV Censored Group" as your scraper with default settings, it will prefer R18.com as the source for actors. R18.com has this movie with only 1 actor listed, so that's what the scaper returned. You can either change your amalgamating settings (from the settings menu) to not prefer R18.com or manually use a different scraper for this movie.
