### ISSUE TITLE
Create a Heydouga scrapper

### ISSUE THREAD

**Issue by brunho** [DoctorD1501/JAVMovieScraper#135]
Good evening
a improvemend of  JAVMS would scrapping movies of  Heydouga.com

Thanx a lot for yours work , JAVMS help me :)

**Comment by DoctorD1501** [comment]
Hey Brunho,

This site just has movies from other sites, right? And the quality of the data seems pretty bad, with low quality thumbnails, actors without commas between their names so I can't separate them, etc. Not to mention the ID given to each movie is somewhat incomprehensible and just would be based off the URL. Googling for the movie name wouldn't work either because the movie names they give to most movies is so short.

I think it's better to get the data from other sites that have higher quality data. If you feel differently, let me know why HeyDouga is a good site for metadata, or what they have that is better than other sites.

**Comment by DoctorD1501** [comment]
Also, this is a duplicate request of #40.

**Comment by Wizell** [comment]
Please use the new "Request new scraper" in order to help me with scraper creation/maintenance
