### ISSUE TITLE
R18 Scraper broken

### ISSUE THREAD

**Issue by unknown12345678** [DoctorD1501/JAVMovieScraper#143]
Since I recently updated to a newer build about a week or two ago I noticed that information is not getting scraped from R18.com.

Specifically - Year, Release Date, Plot. Potentially more info as well (trailer link?). 

Had no issues until I updated the build. 

You can test using this title ID as an example - PGD-871

**Comment by unknown12345678** [comment]
Upon further inspection, I tried rolling back to an old Nov 2015 build and have the same issue. Perhaps R18 have changed their website and the program parameters need to be updated?

**Comment by DoctorD1501** [comment]
Yeah, things have broken a bit. Good news is that I already made some fixes in my latest beta build to fix release date and year. I'm not sure about plot yet - can you provide the URL of a movie on r18 that has a plot that is no longer scraping? Most movies seem not to have plots there, so it's hard to find one. 

My newest beta build is SUPER experimental because I'm making massive changes to fix some memory allocation. It's going to be a little bit before I make an official release with it.

However, if you'd like to be on the bleeding edge, you can download it and try it out:

http://www.mediafire.com/download/pm3d2yl49qa99fe/JAVMovieScraper.jar

**Comment by DoctorD1501** [comment]
Also, let me know if any R18 movies are still breaking, even with the newest beta release.

Thanks!

**Comment by unknown12345678** [comment]
I haven't had a movie that didn't scrape properly contain a plot. Not many movies contain plots so it'll be hard to identify. Once I come across one I will let you know for sure. 

Certainly I will test the new build and keep you posted.

Appreciate all the hard work. This app is a lifesaver and I couldn't live without it. Happy to make a donation and support its progress even further.

**Comment by DoctorD1501** [comment]
I'm glad to hear you're getting good use out of the app. No donations needed - just continue to make bug reports if you notice any.

Thanks,
DoctorD

**Comment by DoctorD1501** [comment]
Should be fixed in 210c8c466e0f5b028e4bfc3e03bc3bbda82ff0b3. Closing the issue.

**Comment by unknown12345678** [comment]
Just noticed even with the new build, it would not scrape the year and release date for this R18 title: BLK-184

**Comment by DoctorD1501** [comment]
It seems ok for me when I try it? Maybe grab the newest release off the release page and try again, just in case, since I've made a new release there last night.

Do you see any errors in the console log?

**Comment by unknown12345678** [comment]
Just grabbed newest release and now appears to be working. Unsure what happened but I'm certain it didn't work in yesterdays build.
