### ISSUE TITLE
Javlibrary isn't being scraped

### ISSUE THREAD

**Issue by javsat** [DoctorD1501/JAVMovieScraper#239]
When I try to scrape from Javlibrary, it just cycles through but doesn't actually grab any data or images. I noticed they have implemented cloudflare and I'm wondering if that might be preventing it. Any solution?

**Comment by DarkMask100** [comment]
JavLibrary moved to Cloudflare so either an existing solution will need to be incorporated or the devs will have to come up with their own to bypass it.

**Comment by standing100** [comment]
Wasn't JavLib not for long time using cloudflare?

JavLib has the most completed actor names, using the other scrapers / the JAV censored group it often returns "" as actor (nothing because its not filled or filled as "amateur")

Maybe adding acount support for JavLib can bye-pass cloudflare problems?

**Comment by unknown12345678** [comment]
+1 for hoping this gets a fix. Much appreciated.

**Comment by fidofido300** [comment]
:+1:

**Comment by Wizell** [comment]
I do have a working code now. I will merge it for the next release

**Comment by zeldatp151** [comment]
Awesome!

**Comment by unknown12345678** [comment]
@Wizell thanks for the work. Is there an ETA when the next release will be available? Completely understand if you're busy because of the holiday season and all.

**Comment by Wizell** [comment]
The 0.3.5 release contains code that should make javlibrary scraper works again.
