### ISSUE TITLE
Create a scraper for JavBus

### ISSUE THREAD

**Issue by Renaix** [DoctorD1501/JAVMovieScraper#56]
http://www.javbus.com/en really useful site with a lot of JAV movies (even some that I couldn't find on other sites), sorted by both censored and uncensored.

**Comment by DoctorD1501** [comment]
Seems like a pretty cool site, especially because it has a lot of uncensored content that I don't need to write a million different scrapers for. It's too bad they don't have the title in English all the time, but I can always run it through the translate function like I do for DMM. I'll try to add this site at some point to the scraper.

**Comment by Renaix** [comment]
Great, looking forward to it!

**Comment by DoctorD1501** [comment]
Scraper has now been added.
