### ISSUE TITLE
Extremely slow on network drive

### ISSUE THREAD

**Issue by shad00m** [DoctorD1501/JAVMovieScraper#8]
The program freezes after every click on anything on a network drive in windows for a couple of seconds. Moving takes about 30 seconds or more where when its attached directly via USB only takes less than 1 second.

**Comment by DoctorD1501** [comment]
I'm going to close this issue for now as I've made many performance tweaks since it was opened. It seems usable to me on my own network drive in terms of performance. If you're still having problems with performance on the newest build, let me know by leaving a new comment in this issue or open a new one.

Thanks.
